### PR TITLE
Add types for TS

### PR DESCRIPTION
**Pull request by IGoRFonin**
Hey.
When conversion a project to the TS, I encountered with error of types. Add types.

### CODE REVIEW

**Comment by growlycode** [comment]
Resolves #76

**Comment by ns3777k** [comment]
any chance to merge and publish in the near future ? :smiley:

**Comment by gnarf** [comment]
Thanks - sorry for the long delay in working on these issues - Z has been working hard on hard-source-webpack-plugin and I've been forgetting to check this repo!

**Comment by ns3777k** [comment]
thanks!

**Pull request merged**
