### PR TITLE
TypeScript typings

### PR DESCRIPTION
**Pull request by jmfirth**
Initial definitions for #27.  I don't have any experience with this library so you might want to spot check.  Usage tests within.

### CODE REVIEW

**Comment by jmfirth** [comment]
The state type `S` could be removed but I am hesitant to do so as I presume you intend to support state features soon.  If that's the case, typing things properly in advance will alleviate a great number of soon-to-be broken test cases.

**Comment by jmfirth** [comment]
Configuring CI to check TypeScript definitions and usage source is trivial but there is a snag: the current version of preact (8.1.0) has a bug in the type definitions that will break it; fixed in a merged but as-yet unreleased PR https://github.com/developit/preact/pull/740.  

Leaving this patch here in case I forget to submit a PR for it later:

`typescript-validation.diff`
```diff
diff --git a/package.json b/package.json
index 4581c80..8035cf4 100644
--- a/package.json
+++ b/package.json
@@ -11,7 +11,8 @@
   "scripts": {
     "test-jest": "jest --config jest.config.json",
     "test-jest-webpack": "jest-webpack",
-    "test": "npm run test-jest && npm run test-jest-webpack",
+    "test-typescript": "tsc --noEmit",
+    "test": "npm run test-jest && npm run test-jest-webpack && npm run test-typescript",
     "pretest": "npm run lint",
     "lint": "eslint --ignore-pattern='!.eslintrc.js' --ext js,jsx src .eslintrc.js *.js"
   },
```
`git apply typescript-validation.diff`

**Comment by gnarf** [comment]
Nice! Thanks for getting this started

**Comment by gnarf** [comment]
Do you happen to know of another TypeScript person who could help put a second set of eyes on this PR just to help land it? 😎

**Comment by gnarf** [comment]
Took this as is for now, if there are any updates to it later, we will take them, and try to figure out how to maintain this ourselves long term :)

**Pull request merged**
