### PR TITLE
Add component(), setState(), state() methods

### PR DESCRIPTION
**Pull request by gnarf**
This is a PR to try to address #39.

It allows getting the component and manipulating states from a single node FindWrapper.

Thoughts @mzgoddard ?

@brunoscopelliti can you test out the branch and see if it helps your issue?

### CODE REVIEW

**Comment by gnarf** [comment]
An intersting thing to note in the documentation, is that the `.component()` returns the "Spied" subclass, but I'm not sure theirs any way around this.... It shouldn't matter much anyway since it's a subclass.

**Comment by brunoscopelliti** [comment]
@gnarf Sure!

**Comment by brunoscopelliti** [comment]
I've tried to use the methods you've now exposed, and they seem to work fine.
I get the result I expected.

Thanks for having taken immediate action on this.

**Comment by mzgoddard** [comment]
@gnarf I think we need to add a `componentWillUnmount` override to the class spies to unset the componentMap key for that spy when a context is re-rendered. We need to ensure you can't get a component with `.component` that doesn't exist anymore.

Maybe we don't need the `Unmount` handle. We need a test to ensure you can't get a no longer existing component. I believe in the current change in this PR you could get the `.component()` for an existing FindWrapper, even if the component no longer exists in the spied dom.

**Comment by gnarf** [comment]
> Maybe we don't need the Unmount handle. We need a test to ensure you can't get a no longer existing component. I believe in the current change in this PR you could get the .component() for an existing FindWrapper, even if the component no longer exists in the spied dom.

Hrm... so this brings up an interesting scenario...

```jsx

const context = shallow(<div><MyComponent /></div>);

const myComponent = context.find('MyComponent');
context.render(<div><MyComponent /></div>);
```
technically, at this point, `MyComponent` no longer maps to that first "found" `MyComponent` vdom instance, it's now tied to the new one.

I can totally see the "unmount" issue as well, but should all the old "find"s be invalidated for the components?

**Comment by gnarf** [comment]
I think the "interesting" thing is that basically holding onto any `.find()` result is probably a bad idea, if anything re-renders, you're working against an "old vdom" version.

**Comment by mzgoddard** [comment]
Yeah I think we should advise against holding `.find()`s between renders or state changes. Outside cases we explicitly make error there could still be issues leading to tests, testing the old environment.

I think it'd be fine to invalidate all `.find()`s after any change to the dom. That would handle this case and any other ones that could come up and give false positives or false negatives.

**Comment by mzgoddard** [comment]
We could invalidate by having a `renderRevision` on the `Context` and on the `Wrappers`. If the revision is different between the wrapper and its context, it should error on any request.

**Comment by brunoscopelliti** [comment]
At the moment I'm not of help with the code, but if you need any help with testing just give me a shout.

**Comment by gnarf** [comment]
I tweaked the setup for the console.warn to track a `vdomRevision` any time one of the spies renders (stuck it in the `setVDom` helper) instead of verifying that the found nodes are still reachable, this should make the comparison both faster, and more "true" for determining "stale"ness

**Pull request merged**
